import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* <Header /> */}
      {/* tailwindcss로 font-sans라고 지정해주면 pretendard 폰트로 보여줌 */}
      <body className={`${pretendard.variable} font-sans`}>
        {/* ✅ TODO: 전역 Provider 감싸기 */}
        {children}
      </body>
      {/* <Footer /> */}
    </html>
  );
}
